=== fabiosl/neoclinica/trunk/documentos/ModeloTarefa/GerenciarPaciente/TAME.dtd
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Pedro Barbosa Cordeiro (HOME) -->
<!ELEMENT model (taskTree, objects, agents, tools, things, situations, methods)>
<!ATTLIST model
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT taskTree (task)>
<!-- Dynamic concepts -->
<!ELEMENT task (preSituation, postSituation, howToPerform, additionalAttribute*, (task | action)*)>
<!ATTLIST task
	number CDATA #REQUIRED
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	duration CDATA #REQUIRED
	frequency CDATA #REQUIRED
	importance CDATA #REQUIRED
	interruptability CDATA #REQUIRED
	modality CDATA #REQUIRED
	occurrence CDATA #REQUIRED
	type CDATA #REQUIRED
	priority CDATA #REQUIRED
>
<!ELEMENT action (preSituation, postSituation, actionAgents, actionTools, actionThings, additionalAttribute*)>
<!ATTLIST action
	number CDATA #REQUIRED
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	duration CDATA #REQUIRED
	frequency CDATA #REQUIRED
	importance CDATA #REQUIRED
	interruptability CDATA #REQUIRED
	modality CDATA #REQUIRED
	occurrence CDATA #REQUIRED
	type CDATA #REQUIRED
	priority CDATA #REQUIRED
	status CDATA #REQUIRED
>
<!-- Static concepts -->
<!ELEMENT object (components, additionalAttribute*)>
<!ATTLIST object
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
>
<!ELEMENT agent (components, competences, additionalAttribute*)>
<!ATTLIST agent
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
	computationalExperience CDATA #REQUIRED
	taskExperience CDATA #REQUIRED
>
<!ELEMENT tool (components, applying, operators, additionalAttribute*)>
<!ATTLIST tool
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
>
<!ELEMENT thing (components, characteristics, additionalAttribute*)>
<!ATTLIST thing
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
>
<!ELEMENT situation (situationObjects, howToObtain, additionalAttribute*)>
<!ATTLIST situation
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
	restriction CDATA #REQUIRED
>
<!ELEMENT method (additionalAttribute*)>
<!ATTLIST method
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
	body CDATA #REQUIRED
>
<!-- Remainder elements -->
<!-- Objects that would compound an object -->
<!ELEMENT components (reference*)>
<!-- Actions that an agent would Perform -->
<!ELEMENT competences (reference*)>
<!-- Actions in wich a tool would be used -->
<!ELEMENT applying (reference*)>
<!-- Agents that would use a tool to Perform an action -->
<!ELEMENT operators (reference*)>
<!--  -->
<!ELEMENT characteristics (reference*)>
<!-- Actions that lead to a situation -->
<!ELEMENT howToObtain (reference*)>
<!-- Methods that tell how a task would be Performed -->
<!ELEMENT howToPerform (reference*)>
<!-- Pre situation of a dynamic concept -->
<!ELEMENT preSituation (reference*)>
<!-- Post situation of a dynamic concept -->
<!ELEMENT postSituation (reference*)>
<!-- Tools used to perform actions -->
<!ELEMENT actionTools (reference*)>
<!-- agents that perform actions -->
<!ELEMENT actionAgents (reference*)>
<!-- situations' objects -->
<!ELEMENT situationObjects (reference*)>
<!-- concepts' additional attributes -->
<!ELEMENT additionalAttribute EMPTY>
<!ATTLIST additionalAttribute
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!ELEMENT reference EMPTY>
<!ATTLIST reference
	name CDATA #REQUIRED
>
<!ELEMENT objects (object*)>
<!ELEMENT agents (agent*)>
<!ELEMENT tools (tool*)>
<!ELEMENT things (thing*)>
<!ELEMENT situations (situation*)>
<!ELEMENT methods (method*)>

=== fabiosl/neoclinica/trunk/documentos/ModeloTarefa/UsarSistema/UsarSistemamodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "TAME.dtd">
<model name="" description="">
<taskTree>
<task number="1" name="Usar Sistema" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Usar Sistema" />
<reference name="Method task Usar Sistema 1" />
</howToPerform>
<task number="1.1" name="Efetuar Login" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Efetuar Login 1.1" />
</howToPerform>
<action number="1.1.1" name="Inf. Login" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.2" name="Inf Senha" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.3" name="Confirmar" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.4" name="Cancelar" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<action number="1.2" name="Ger Contas" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3" name="Ger Pacientes" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.4" name="Ger Lentes" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.5" name="Ger Relatorios" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
</taskTree>
<objects />
<agents />
<tools />
<things />
<situations />
<methods />
</model>

=== fabiosl/neoclinica/trunk/documentos/ModeloTarefa/GerenciarLentes/gerenciarLentesmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "TAME.dtd">
<model name="" description="">
<taskTree>
<task number="1" name="Ger Est Lentes" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Ger Est Lentes" />
<reference name="Method task Ger Est Lentes 1" />
</howToPerform>
<task number="1.1" name="Cadastrar Lente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Cadastrar Lente 1.1" />
</howToPerform>
<action number="1.1.1" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.2" name="Inf Preco" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.3" name="Inf Medico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.4" name="Inf Qtd" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.5" name="Ger Codigo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.2" name="Remover Lente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Remover Lente 1.2" />
</howToPerform>
<action number="1.2.1" name="Inf codigo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.2" name="Inf Medico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.3" name="Inf Qtd" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.3" name="Cons Estoque" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Cons Estoque" />
</howToPerform>
<action number="1.3.1" name="Inf Medico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.2" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.3" name="Inf Marca" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.4" name="Modificar lente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Modificar lente 1.4" />
</howToPerform>
<action number="1.4.1" name="Inf Dados Antigos" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.4.2" name="Inf Dados Novos" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
</task>
</taskTree>
<objects />
<agents />
<tools />
<things />
<situations />
<methods>
<method name="Method task Ger Est Lentes" description="" instant="0" body="SEQ(Cadastrar Lente, Remover Lente, Consultar Estoque, Modificar lente)" />
<method name="Method task Cadastrar Lente 1.1" description="" instant="0" body="SEQ(AND(Inf Nome, Inf Preco,Inf Medico,Inf Qtd), Ger Codigo)" />
<method name="Method task Remover Lente 1.2" description="" instant="0" body="SEQ(AND(Inf codigo, Inf Medico), Inf Qtd)" />
<method name="Method task Cons Estoque" description="" instant="0" body="SEQ(Inf Medico, Inf Nome, Inf Marca)" />
<method name="Method task Ger Est Lentes 1" description="" instant="0" body="SEQ(OR(Cadastrar Lente, Remover Lente,Cons Estoque), Modificar lente)" />
<method name="Method task Modificar lente 1.4" description="" instant="0" body="SEQ(Inf Dados Antigos, Inf Dados Novos)" />
</methods>
</model>

=== fabiosl/neoclinica/documentos/ModeloTarefa/GerenciarContas/gerenciarContasmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "TAME.dtd">
<model name="" description="">
<taskTree>
<task number="1" name="Ger Contas" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Ger Contas 1" />
</howToPerform>
<task number="1.1" name="Ad. Secretaria" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Ad. Secretaria 1.1" />
</howToPerform>
<action number="1.1.1" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.2" name="Inf Salario" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.3" name="Inf. N. CTPS" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.4" name="Inf CPF" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.5" name="Inf Data Admissao" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.6" name="Confirmar" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.7" name="Cancelar" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.2" name="Ad. Médico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Ad. Médico 1.2" />
</howToPerform>
<action number="1.2.1" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.2" name="Inf CRM" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.3" name="Inf CPF" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.4" name="Confirmar" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.5" name="Cancelar" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
</task>
</taskTree>
<objects />
<agents />
<tools />
<things />
<situations />
<methods>
<method name="Method task Ger Contas 1" description="" instant="0" body="SEQ(Ad. Secretaria, Ad. Médico)" />
<method name="Method task Ad. Secretaria 1.1" description="" instant="0" body="SEQ(Inf Nome, Inf Salario, Inf. N. CTPS, Inf CPF, Inf Data Admissao, XOR(Confirmar, Cancelar))" />
<method name="Method task Ad. Médico 1.2" description="" instant="0" body="SEQ(Inf Nome, Inf CRM, Inf CPF, XOR(Confirmar, Cancelar))" />
</methods>
</model>

=== fabiosl/neoclinica/trunk/documentos/ModeloTarefa/GerenciarFornecedor/GerenciarFornecmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "TAME.dtd">
<model name="" description="">
<taskTree>
<task number="1" name="Ger Fornecedor" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Ger Fornecedor 1" />
</howToPerform>
<task number="1.1" name="Ad. Fornec" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Ad. Fornec 1.1" />
</howToPerform>
<action number="1.1.1" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.2" name="Inf Lentes" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.3" name="Inf CNPJ" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.4" name="Inf Telefone" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.5" name="Inf email" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.6" name="Ger Codigo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.2" name="Pesq Fornec" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Pesq Fornec 1.2" />
</howToPerform>
<action number="1.2.1" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.2" name="Inf Lente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.3" name="Remover Fornec" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Remover Fornec 1.3" />
</howToPerform>
<action number="1.3.1" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.2" name="Inf Codigo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.4" name="Modif Fornec" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Modif Fornec 1.4" />
</howToPerform>
<action number="1.4.1" name="Inf Dado Antigo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.4.2" name="Inf Dado Novo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
</task>
</taskTree>
<objects />
<agents />
<tools />
<things />
<situations />
<methods>
<method name="Method task Ger Fornecedor 1" description="" instant="0" body="SEQ(Ad. Fornec, Pesq Fornec, Remover Fornec, Modif Fornec)" />
<method name="Method task Ad. Fornec 1.1" description="" instant="0" body="SEQ(AND(Inf Nome, Inf Lentes,Inf CNPJ,Inf Telefone,Inf email), Ger Codigo)" />
<method name="Method task Pesq Fornec 1.2" description="" instant="0" body="SEQ(Inf Nome, Inf Lente)" />
<method name="Method task Remover Fornec 1.3" description="" instant="0" body="SEQ(Inf Nome, Inf Codigo)" />
<method name="Method task Modif Fornec 1.4" description="" instant="0" body="SEQ()" />
</methods>
</model>
