=== fabiosl/neoclinica/trunk/documentos/ModeloTarefa/GerenciarPaciente/TAME.dtd
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Pedro Barbosa Cordeiro (HOME) -->
<!ELEMENT model (taskTree, objects, agents, tools, things, situations, methods)>
<!ATTLIST model
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT taskTree (task)>
<!-- Dynamic concepts -->
<!ELEMENT task (preSituation, postSituation, howToPerform, additionalAttribute*, (task | action)*)>
<!ATTLIST task
	number CDATA #REQUIRED
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	duration CDATA #REQUIRED
	frequency CDATA #REQUIRED
	importance CDATA #REQUIRED
	interruptability CDATA #REQUIRED
	modality CDATA #REQUIRED
	occurrence CDATA #REQUIRED
	type CDATA #REQUIRED
	priority CDATA #REQUIRED
>
<!ELEMENT action (preSituation, postSituation, actionAgents, actionTools, actionThings, additionalAttribute*)>
<!ATTLIST action
	number CDATA #REQUIRED
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	duration CDATA #REQUIRED
	frequency CDATA #REQUIRED
	importance CDATA #REQUIRED
	interruptability CDATA #REQUIRED
	modality CDATA #REQUIRED
	occurrence CDATA #REQUIRED
	type CDATA #REQUIRED
	priority CDATA #REQUIRED
	status CDATA #REQUIRED
>
<!-- Static concepts -->
<!ELEMENT object (components, additionalAttribute*)>
<!ATTLIST object
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
>
<!ELEMENT agent (components, competences, additionalAttribute*)>
<!ATTLIST agent
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
	computationalExperience CDATA #REQUIRED
	taskExperience CDATA #REQUIRED
>
<!ELEMENT tool (components, applying, operators, additionalAttribute*)>
<!ATTLIST tool
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
>
<!ELEMENT thing (components, characteristics, additionalAttribute*)>
<!ATTLIST thing
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
>
<!ELEMENT situation (situationObjects, howToObtain, additionalAttribute*)>
<!ATTLIST situation
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
	restriction CDATA #REQUIRED
>
<!ELEMENT method (additionalAttribute*)>
<!ATTLIST method
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	instant CDATA #REQUIRED
	body CDATA #REQUIRED
>
<!-- Remainder elements -->
<!-- Objects that would compound an object -->
<!ELEMENT components (reference*)>
<!-- Actions that an agent would Perform -->
<!ELEMENT competences (reference*)>
<!-- Actions in wich a tool would be used -->
<!ELEMENT applying (reference*)>
<!-- Agents that would use a tool to Perform an action -->
<!ELEMENT operators (reference*)>
<!--  -->
<!ELEMENT characteristics (reference*)>
<!-- Actions that lead to a situation -->
<!ELEMENT howToObtain (reference*)>
<!-- Methods that tell how a task would be Performed -->
<!ELEMENT howToPerform (reference*)>
<!-- Pre situation of a dynamic concept -->
<!ELEMENT preSituation (reference*)>
<!-- Post situation of a dynamic concept -->
<!ELEMENT postSituation (reference*)>
<!-- Tools used to perform actions -->
<!ELEMENT actionTools (reference*)>
<!-- agents that perform actions -->
<!ELEMENT actionAgents (reference*)>
<!-- situations' objects -->
<!ELEMENT situationObjects (reference*)>
<!-- concepts' additional attributes -->
<!ELEMENT additionalAttribute EMPTY>
<!ATTLIST additionalAttribute
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!ELEMENT reference EMPTY>
<!ATTLIST reference
	name CDATA #REQUIRED
>
<!ELEMENT objects (object*)>
<!ELEMENT agents (agent*)>
<!ELEMENT tools (tool*)>
<!ELEMENT things (thing*)>
<!ELEMENT situations (situation*)>
<!ELEMENT methods (method*)>

=== fabiosl/neoclinica/documentos/ModeloTarefa/GerenciarConsulta/gerenciarConsultamodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "TAME.dtd">
<model name="" description="">
<taskTree>
<task number="1" name="Gerenciar Consulta" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Gerenciar Consulta" />
<reference name="Method task Gerenciar Consulta 1" />
</howToPerform>
<task number="1.1" name="Marcar Consulta" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Marcar Consulta 1.1" />
</howToPerform>
<action number="1.1.1" name="Inf Paciente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.2" name="Inf Medico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.3" name="Inf Horario" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.2" name="Remover Consulta" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Remover Consulta 1.2" />
</howToPerform>
<action number="1.2.1" name="Inf Paciente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.2" name="Inf Medico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.3" name="Inf Horario" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.3" name="Localizar Consulta" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Localizar Consulta 1.3" />
</howToPerform>
<action number="1.3.1" name="Inf Médico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.2" name="Inf Paciente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.3" name="Inf Data" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
</task>
</taskTree>
<objects />
<agents />
<tools />
<things />
<situations />
<methods>
<method name="Method task Gerenciar Consulta" description="" instant="0" body="SEQ(Inf Paciente, Inf Medico, Inf Horario, XOR(Confirmar, Cancelar))" />
<method name="Method task Gerenciar Consulta 1" description="" instant="0" body="SEQ(Marcar Consulta, Remover Consulta, Localizar Consulta)" />
<method name="Method task Marcar Consulta 1.1" description="" instant="0" body="SEQ(Inf Paciente, Inf Medico, Inf Horario)" />
<method name="Method task Remover Consulta 1.2" description="" instant="0" body="SEQ(Inf Paciente, Inf Medico, Inf Horario)" />
<method name="Method task Localizar Consulta 1.3" description="" instant="0" body="SEQ(Inf Médico, Inf Paciente, Inf Data)" />
</methods>
</model>

=== fabiosl/neoclinica/documentos/ModeloTarefa/GerenciarPaciente/GerenciarPacientemodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "TAME.dtd">
<model name="" description="">
<taskTree>
<task number="1" name="Ger Pacientes" description="asdasd" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Ger Pacientes 1" />
</howToPerform>
<task number="1.1" name="Cadastrar Paciente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Cadastrar Paciente 1.1" />
</howToPerform>
<action number="1.1.1" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,n)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.2" name="Inf Data Nasc" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(1,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.3" name="Inf Email" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,n)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.4" name="Inf Telefones" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,n)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.5" name="inf RG" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.6" name="Inf CPF" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.7" name="Inf Endereco" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,n)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.8" name="Inf Convenio" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.9" name="Inf ExtID" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.10" name="Ger Codigo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.2" name="Remover Paciente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform />
<action number="1.2.1" name="Inf ExtID" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.3" name="Pesquisar Pac" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Pesquisar Pac 1.3" />
</howToPerform>
<action number="1.3.1" name="Inf Nome" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,n)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.2" name="Inf CPF" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.3" name="Inf RG" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.4" name="inf email" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,n)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.3.5" name="Inf Data Nasc" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.4" name="Modific Pac" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Modific Pac 1.4" />
</howToPerform>
<action number="1.4.1" name="Inf Dados Ant" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,n)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.4.2" name="Inf Dados Novos" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,n)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
</task>
</taskTree>
<objects />
<agents />
<tools />
<things />
<situations />
<methods>
<method name="Method task Ger Pacientes 1" description="" instant="0" body="SEQ(OR(Cadastrar Paciente, Remover Paciente,Pesquisar Pac), Modific Pac)" />
<method name="Method task Cadastrar Paciente 1.1" description="" instant="0" body="SEQ(Inf Nome, Inf Data Nasc, Inf Email, Inf Telefones, inf RG, Inf CPF, Inf Endereco, Inf Convenio, Inf ExtID, Ger Codigo)" />
<method name="Method task Pesquisar Pac 1.3" description="" instant="0" body="SEQ(Inf Nome, Inf CPF, Inf RG, inf email, Inf Data Nasc)" />
<method name="Method task Modific Pac 1.4" description="" instant="0" body="SEQ(Inf Dados Ant, Inf Dados Novos)" />
</methods>
</model>

=== fabiosl/neoclinica/documentos/ModeloTarefa/GerenciarRelatorios/gerenciarRelatoriosmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "TAME.dtd">
<model name="" description="">
<taskTree>
<task number="1" name="Ger Relatorios" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Ger Relatorios 1" />
</howToPerform>
<task number="1.1" name="Exib Relat Lent" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Exib Relat Lent 1.1" />
</howToPerform>
<action number="1.1.1" name="Inf Medico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.2" name="Inf Fornecedor" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.3" name="Informar Lente" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.1.4" name="Inf Periodo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
<task number="1.2" name="Exib Relat Pac" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0">
<preSituation />
<postSituation />
<howToPerform>
<reference name="Method task Exib Relat Pac 1.2" />
</howToPerform>
<action number="1.2.1" name="Inf Medico" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.2" name="Inf Nome Pac" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.3" name="Inf Periodo" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
<action number="1.2.4" name="Inf Convenio" description="" duration="0" frequency="High" importance="High" interruptability="No interruptible" modality="Manual" occurrence="(0,1)" type="Mental" priority="0" status="">
<preSituation />
<postSituation />
<actionAgents />
<actionTools />
<actionThings />
</action>
</task>
</task>
</taskTree>
<objects />
<agents />
<tools />
<things />
<situations />
<methods>
<method name="Method task Ger Relatorios 1" description="" instant="0" body="SEQ(ask(Exib Relat Lent, Exib Relat Pac))" />
<method name="Method task Exib Relat Pac 1.2" description="" instant="0" body="SEQ(Inf Medico, Inf Nome Pac, Inf Periodo, Inf Convenio)" />
<method name="Method task Exib Relat Lent 1.1" description="" instant="0" body="SEQ(Inf Medico, Inf Fornecedor, Informar Lente, Inf Periodo)" />
</methods>
</model>
